### ISSUE TITLE
mod cant load 

### ISSUE THREAD

**Issue by Labbit35** [XtarsAgency/Zeridmuth#20]
apparently there's a extra } or sum shit like that. Anyways the mod can't load properly

**Comment by ItzCraft** [comment]
Download not by clicking button "Download", Download latest release and it will work. If mod with downloaded latest version still dont work send error with mod to our discord server.

**Comment by XtarsAgency** [comment]
What part of it exactly? Explain it, it shows on the mod that thingy, tell us what it says

**Comment by Labbit35** [comment]
「Uhh, dont specify ***@***.***>」在 2023年11月23日 週四，下午10:55 寫道：

**Comment by XtarsAgency** [comment]
Hold on, we are fixing the issue, its on the turret. You can enjoy the game a short moment from now, we're going to inform you soon

**Comment by Labbit35** [comment]
Cool

「Uhh, dont specify ***@***.***>」在 2023年11月23日 週四，下午11:04 寫道：

**Comment by XtarsAgency** [comment]
Okay, you can try the mod now, the issue has been resolved

**Comment by Labbit35** [comment]
Bruh

「Uhh, dont specify ***@***.***>」在 2023年11月23日 週四，下午11:21 寫道：

**Comment by ItzCraft** [comment]
Sorry, issue not resolved. Just download latest release of mod. We will try fix it.

**Comment by Labbit35** [comment]
No problem take your time.

「ItzCraft ***@***.***>」在 2023年11月23日 週四，下午11:36 寫道：

**Comment by ItzCraft** [comment]
Now problem fixed.

**Comment by Labbit35** [comment]
Bruh

「ItzCraft ***@***.***>」在 2023年11月24日 週五，下午10:46 寫道：

**Comment by ItzCraft** [comment]
Sorry, just wait to XtarsAgency accept pull request and its will be fixed.

**Comment by Labbit35** [comment]
Ok

「ItzCraft ***@***.***>」在 2023年11月25日 週六，下午5:26 寫道：

**Comment by ItzCraft** [comment]
Ok fixed now

**Comment by Labbit35** [comment]
I think there’s some domino effect in the code
「ItzCraft ***@***.***>」在 2023年11月25日 週六，下午6:28 寫道：

**Comment by XtarsAgency** [comment]
Fixed it, try now

**Comment by XtarsAgency** [comment]
Hey, if you have another issue, please join our discord server so its easier for us

**Comment by Labbit35** [comment]
Ok

「Uhh, dont specify ***@***.***>」在 2023年11月25日 週六，下午7:40 寫道：

**Comment by Labbit35** [comment]
Link doesn’t work


「Uhh, dont specify ***@***.***>」在 2023年11月25日 週六，下午7:40 寫道：

**Comment by ItzCraft** [comment]
https://discord.com/invite/KuV5r39cpY

**Comment by ItzCraft** [comment]
Try it
