### ISSUE TITLE
boot crash mod unplayable

### ISSUE THREAD

**Issue by MrGoblin1401** [XtarsAgency/Zeridmuth#3]
crashes before game even loads completely unplayable i don't recommend downloading this mod until that issue is addressed for context i am on pc not on mobile so its not a mobile or android issue

**Comment by XtarsAgency** [comment]
Its better to download the latest release, not the latest update, because this one is experimental. You should download Release v.0.1.7.6-beta instead. The latest update is for devs like me, im currently trying to work out the issue and that is the custom "seeker" core.

**Comment by XtarsAgency** [comment]
Fixed, it was some random HJSON code dingling somewhere that i forgot.
