### ISSUE TITLE
Something wrong with code

### ISSUE THREAD

**Issue by justRive** [XtarsAgency/Zeridmuth#40]
When I try to play with "A new beginning" I get error "(did you forget a closing '}'?) at 86:-1"
Please fix it.
![Screenshot_2024-06-08-13-11-55-63_13f989b68d7412e5a177fb13b36ac66f](https://github.com/XtarsAgency/Zeridmuth/assets/171754004/861a8997-1a7e-412c-a2f0-17fbe6a60651)
![Screenshot_2024-06-08-13-12-02-52_13f989b68d7412e5a177fb13b36ac66f](https://github.com/XtarsAgency/Zeridmuth/assets/171754004/852da1ce-863a-4bfe-ada9-b414c7b658a5)
![Screenshot_2024-06-08-13-12-27-46_13f989b68d7412e5a177fb13b36ac66f](https://github.com/XtarsAgency/Zeridmuth/assets/171754004/7a402ea6-6f41-4be0-a1f6-b82284d9717c)

**Comment by XtarsAgency** [comment]
Fixed

**Comment by justRive** [comment]
Thanks 🤗
