### ISSUE TITLE
Just read. 

### ISSUE THREAD

**Issue by ItzCraft** [XtarsAgency/Zeridmuth#5]
uhh hello. Idk why but I want help you with working on this mod. (if you ask me "Who are you?" I will answer: just a random hjson mindustry mod maker) because work on mod in duo it's better then in solo (I think)

**Comment by XtarsAgency** [comment]
Hi! So im Fomahault Coredemshau (not my real name) and i make this mod also sometimes in duo, a bit with "YoruKitsune" but its nice to have you to join with someone new. You can ping me on discord @FomahaultCoredemshau
Thanks for asking, and i also need some contributions for the mod, also, what is your discord name? So i know its you requesting in discord?

**Comment by ItzCraft** [comment]
My discord is: "ItzCraft"
